//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyDesignations = new HashSet<CompanyDesignation>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
            this.CompanyHolidays = new HashSet<CompanyHoliday>();
            this.EmployeeDevices = new HashSet<EmployeeDevice>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.ProjectMembers = new HashSet<ProjectMember>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime EstablishedDate { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string TinNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public bool IsActive { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual CompanyContact CompanyContact { get; set; }
        public virtual ICollection<CompanyDesignation> CompanyDesignations { get; set; }
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
        public virtual ICollection<CompanyHoliday> CompanyHolidays { get; set; }
        public virtual ICollection<EmployeeDevice> EmployeeDevices { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
    }
}
