//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEmployee
    {
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public int DesignationId { get; set; }
        public bool IsAdmin { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyDesignation CompanyDesignation { get; set; }
        public virtual User User { get; set; }
    }
}
