//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDesignation
    {
        public CompanyDesignation()
        {
            this.CompanyDesignationRoles = new HashSet<CompanyDesignationRole>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
        }
    
        public int DesignationId { get; set; }
        public string Name { get; set; }
        public int CompanyId { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyContact CompanyContact { get; set; }
        public virtual ICollection<CompanyDesignationRole> CompanyDesignationRoles { get; set; }
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
    }
}
