//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContact
    {
        public CompanyContact()
        {
            this.CompanyDesignations = new HashSet<CompanyDesignation>();
            this.CompanyDevices = new HashSet<CompanyDevice>();
        }
    
        public int CompanyId { get; set; }
        public string Addresss { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string TelPhone1 { get; set; }
        public string TelPhone2 { get; set; }
        public bool isActive { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CompanyDesignation> CompanyDesignations { get; set; }
        public virtual ICollection<CompanyDevice> CompanyDevices { get; set; }
    }
}
