//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDevice
    {
        public int DeviceId { get; set; }
        public int EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyDevice CompanyDevice { get; set; }
        public virtual User User { get; set; }
    }
}
