//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int LeaveId { get; set; }
        public int EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public string Reason { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public bool IsAllow { get; set; }
        public bool IsFull { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
