//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
            this.EmployeeDevices = new HashSet<EmployeeDevice>();
            this.EmployeesAttandanceDetails = new HashSet<EmployeesAttandanceDetail>();
            this.ProjectMembers = new HashSet<ProjectMember>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string Password1 { get; set; }
        public string Password2 { get; set; }
        public bool IsEmailVerify { get; set; }
        public bool IsMobileVerify { get; set; }
        public bool IsActive { get; set; }
        public int LoginAttempt { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
        public virtual ICollection<EmployeeDevice> EmployeeDevices { get; set; }
        public virtual ICollection<EmployeesAttandanceDetail> EmployeesAttandanceDetails { get; set; }
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
